image: condaforge/mambaforge:23.1.0-1

tasks:
  - name: Initialize
    init: |
      pip install graphviz
      . /opt/conda/etc/profile.d/conda.sh
      conda activate base
      mamba create -n dragonflye-dev -y -q -c conda-forge -c bioconda dragonflye
      conda activate dragonflye-dev
      git checkout main
vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore                 # Language support for .gitignore files
    - cssho.vscode-svgviewer                 # SVG viewer
    - davidanson.vscode-markdownlint         # Markdown/CommonMark linting and style checking for Visual Studio Code
    - eamodio.gitlens                        # Quickly glimpse into whom, why, and when a line or code block was changed
    - EditorConfig.EditorConfig              # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree                  # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv                # Highlight columns in csv files in different colors
    - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow                 # Highlight indentation level
    - streetsidesoftware.code-spell-checker  # Spelling checker for source code
    - anwar.papyrus-pdf                      # PDF preview
