name: dragonflye-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    # At 04:30 on Sunday, Tuesday, and Thursday
    - cron:  '30 4 * * 0,2,4'

jobs:
  dragonflye-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout rpetit3/dragonflye
        uses: actions/checkout@v2

      - name: Checkout bactopia/bactopia-tests repo
        uses: actions/checkout@v2
        with:
          repository: bactopia/bactopia-tests
          ref: bacass
          path: bactopia-tests

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dragonflye
          auto-activate-base: false

      - name: Setup dragonflye Environment
        run: |
          conda install -y -c conda-forge -c bioconda mamba 'python=3.8.0'
          mamba install -y -c conda-forge -c bioconda 'assembly-scan>=0.4.0' any2fasta flye 'kmc>=3.1' 'medaka>=1.5.0' miniasm 'nanoq>=0.8.1' perl perl-file-spec perl-findbin pigz racon rasusa raven-assembler seqtk porechop tensorflow-gpu

      - name: Environment Information
        run: uname -a && env

      - name: Test dragonflye basics
        run: |
          echo "Testing dragonflye"
          bin/dragonflye --version
          bin/dragonflye --help

      - name: Test Raven Assembler (quality filtered)
        run: |
          echo "Test Raven Assembler (quality filtered)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/raven-minquality --gsize 300000 --assembler raven --minquality 8

      - name: Test Raven Assembler (quality filtered, no length filter)
        run: |
          echo "Test Raven Assembler (quality filtered, no length filter)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/raven-minquality-nominreadlen --gsize 300000 --assembler raven --minquality 6 --minreadlen 0

      - name: Test Raven Assembler (quality filtered, no length filter, trimming)
        run: |
          echo "Test Raven Assembler (quality filtered, no length filter)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/raven-minquality-nominreadlen-trim --gsize 300000 --assembler raven --minquality 6 --minreadlen 0 --trim

      - name: Test Raven Assembler (quality filtered, no length filter, trimming, trim opts)
        run: |
          echo "Test Raven Assembler (quality filtered, no length filter)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/raven-minquality-nominreadlen-trimopts --gsize 300000 --assembler raven --minquality 6 --minreadlen 0 --trim --trimopts '--adapter_threshold 95'

      - name: Test Raven Assembler
        run: |
          echo "Testing Raven Assembler"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --depth 5 --outdir tests/raven --gsize 300000 --assembler raven

      - name: Test Raven Assembler + Racon Polish
        run: |
          echo "Testing Raven Assembler + Racon Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-racon --gsize 300000 --assembler raven

      - name: Test Raven Assembler + Medaka Polish
        run: |
          echo "Testing Flye Assembler + Medaka Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-medaka --gsize 300000 --assembler raven --racon 0 --model r103_min_high_g345

      - name: Test Raven Assembler + Racon & Medaka Polish
        run: |
          echo "Testing Flye Assembler + Racon & Medaka Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-both --gsize 300000 --assembler raven

      - name: Test Raven Assembler + Racon & Pilon Polish
        run: |
          echo "Testing Flye Assembler + Racon & Pilon Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --R1 bactopia-tests/data/species/portiera/illumina/SRR2838702_R1.fastq.gz --R2 bactopia-tests/data/species/portiera/illumina/SRR2838702_R2.fastq.gz --cpus 0 --outdir tests/raven-both --gsize 300000 --assembler raven

      - name: Test Flye Assembler
        run: |
          echo "Testing Flye Assembler"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/flye --gsize 300000 --assembler flye
          
      - name: Test Miniasm Assembler
        run: |
          echo "Testing Miniasm Assembler"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 1 --nopolish --outdir tests/miniasm --gsize 300000 --assembler miniasm

      - name: Test --list_models
        run: |
          echo "Testing --list_models"
          bin/dragonflye --list_models 2>&1 | grep r941_min_sup_g507
