name: dragonflye-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  dragonflye-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout rpetit3/dragonflye
        uses: actions/checkout@v2

      - name: Checkout bactopia/bactopia-tests repo
        uses: actions/checkout@v2
        with:
          repository: bactopia/bactopia-tests
          path: bactopia-tests

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: dragonflye
          auto-activate-base: false
          miniforge-version: latest

      - name: Setup dragonflye Environment
        run: |
          conda install -y -c conda-forge -c bioconda 'assembly-scan>=0.4.0' any2fasta bwa dnaapler fastp flye 'kmc>=3.1' 'medaka>=1.11.0' miniasm 'nanoq>=0.8.1' perl perl-file-spec perl-findbin 'polypolish>=0.6.0' pilon pigz racon 'rasusa>=1' raven-assembler samtools samclip seqtk porechop

      - name: Environment Information
        run: uname -a && env

      - name: Test dragonflye basics
        run: |
          echo "Testing dragonflye"
          bin/dragonflye --version
          bin/dragonflye --help

      - name: Test Raven Assembler (quality filtered)
        run: |
          echo "Test Raven Assembler (quality filtered)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --prefix ERR3772599 --cpus 0 --nopolish --outdir tests/raven-minquality --gsize 300000 --assembler raven --minquality 8

      - name: Test Raven Assembler (quality filtered, no length filter)
        run: |
          echo "Test Raven Assembler (quality filtered, no length filter)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/raven-minquality-nominreadlen --gsize 300000 --assembler raven --minquality 6 --minreadlen 0

      - name: Test Raven Assembler (quality filtered, no length filter, trimming)
        run: |
          echo "Test Raven Assembler (quality filtered, no length filter)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/raven-minquality-nominreadlen-trim --gsize 300000 --assembler raven --minquality 6 --minreadlen 0 --trim

      - name: Test Raven Assembler (quality filtered, no length filter, trimming, trim opts)
        run: |
          echo "Test Raven Assembler (quality filtered, no length filter)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/raven-minquality-nominreadlen-trimopts --gsize 300000 --assembler raven --minquality 6 --minreadlen 0 --trim --trimopts '--adapter_threshold 95'

      - name: Test Raven Assembler + Rasusa Depth Filter
        run: |
          echo "Testing Raven Assembler"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --prefix ERR3772599-raven --cpus 0 --nopolish --depth 5 --outdir tests/raven --gsize 300000 --assembler raven

      - name: Test Raven Assembler + Racon Polish
        run: |
          echo "Testing Raven Assembler + Racon Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-racon --gsize 300000 --assembler raven

      - name: Test Raven Assembler + Medaka Polish
        run: |
          echo "Testing Flye Assembler + Medaka Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-medaka --gsize 300000 --assembler raven --racon 0 --model r103_min_high_g345

      - name: Test Raven Assembler + Medaka Polish + --medaka_opts
        run: |
          echo "Testing Flye Assembler + Medaka Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-medaka-opts --gsize 300000 --assembler raven --racon 0 --model r103_min_high_g345 --medaka_opts '-b 200'

      - name: Test Raven Assembler + Racon & Medaka Polish
        run: |
          echo "Testing Flye Assembler + Racon & Medaka Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-both --gsize 300000 --assembler raven

      - name: Test Raven Assembler + Racon & Polypolish Polish
        run: |
          echo "Testing Raven Assembler + Racon & Polypolish Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --R1 bactopia-tests/data/species/portiera/illumina/SRR2838702_R1.fastq.gz --R2 bactopia-tests/data/species/portiera/illumina/SRR2838702_R2.fastq.gz --cpus 0 --outdir tests/raven-polypolish --gsize 300000 --assembler raven

      - name: Test Raven Assembler + Racon & Polypolish Careful Polish
        run: |
          echo "Testing Raven Assembler + Racon & Polypolish Careful Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --R1 bactopia-tests/data/species/portiera/illumina/SRR2838702_R1.fastq.gz --R2 bactopia-tests/data/species/portiera/illumina/SRR2838702_R2.fastq.gz --cpus 0 --outdir tests/raven-polypolish-careful --gsize 300000 --assembler raven --polypolish_careful

      - name: Test Raven Assembler + Racon & Pilon Polish
        run: |
          echo "Testing Raven Assembler + Racon & Pilon Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --R1 bactopia-tests/data/species/portiera/illumina/SRR2838702_R1.fastq.gz --R2 bactopia-tests/data/species/portiera/illumina/SRR2838702_R2.fastq.gz --cpus 0 --outdir tests/raven-pilon --gsize 300000 --assembler raven --polypolish 0 --pilon 1

      - name: Test Miniasm Assembler
        run: |
          echo "Testing Miniasm Assembler"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --prefix ERR3772599_mini.asm --cpus 1 --nopolish --outdir tests/miniasm --gsize 300000 --assembler miniasm

      - name: Test Flye Assembler
        run: |
          echo "Testing Flye Assembler"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --nopolish --outdir tests/flye --gsize 300000 --assembler flye

      - name: Test Flye Assembler (nanohq)
        run: |
          echo "Testing Flye Assembler (with --nano-hq)"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --prefix ERR3772599-nano.hq --cpus 0 --nopolish --outdir tests/flyehq --gsize 300000 --assembler flye --nanohq

      - name: Test --list_models
        run: |
          echo "Testing --list_models"
          bin/dragonflye --list_models 2>&1 | grep r1041_e82_400bps_sup_variant_v4.2.0

      - name: Test Raven Assembler + Medaka Polish + Model version dots
        run: |
          echo "Testing Raven Assembler + Medaka Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-medaka-version-dots --gsize 300000 --assembler raven --racon 0 --model r1041_e82_400bps_sup_variant_v4.2.0

      - name: Test Raven Assembler + Medaka Polish + Model r1041_e82_400bps_sup_g615
        run: |
          echo "Testing Raven Assembler + Medaka Polish"
          bin/dragonflye --reads bactopia-tests/data/species/portiera/nanopore/ERR3772599.fastq.gz --cpus 0 --outdir tests/raven-medaka-version-g615 --gsize 300000 --assembler raven --racon 0 --model r1041_e82_400bps_sup_g615
